version: "3.8"

services:
  orders:
    container_name: "orders"
    hostname: "orders"
    restart: "always"
    ports:
      - "3000:3000"
    networks:
      - "network"
    env_file:
      - "../microservices/orders/.env"
    build:
      context: "../microservices/orders"
      dockerfile: "application.dockerfile"

  orders-subscriber:
    container_name: "orders-subscriber"
    hostname: "orders-subscriber"
    restart: "always"
    networks:
      - "network"
    env_file:
      - "../microservices/orders-subscriber/.env"
    build:
      context: "../microservices/orders-subscriber"
      dockerfile: "subscriber.dockerfile"

  orders-publisher:
    container_name: "orders-publisher"
    hostname: "orders-publisher"
    restart: "always"
    networks:
      - "network"
    env_file:
      - "../microservices/orders-publisher/.env"
    build:
      context: "../microservices/orders-publisher"
      dockerfile: "publisher.dockerfile"

networks:
  network:
    driver: "bridge"
