version: "3.8"

services:
  orders:
    container_name: "orders"
    hostname: "orders"
    restart: "always"
    ports:
      - "3000:3000"
    networks:
      - "network"
    build:
      context: "../microservices/orders"
      dockerfile: "application.dockerfile"

  orders-subscriber:
    container_name: "orders_subscriber"
    hostname: "orders_subscriber"
    restart: "always"
    networks:
      - "network"
    build:
      context: "../microservices/orders_subscriber"
      dockerfile: "subscriber.dockerfile"

  orders-publisher:
    container_name: "orders_publisher"
    hostname: "orders_publisher"
    restart: "always"
    networks:
      - "network"
    build:
      context: "../microservices/orders_publisher"
      dockerfile: "publisher.dockerfile"

networks:
  network:
    driver: "bridge"
